### ISSUE TITLE
Program Beyblade physics

### ISSUE THREAD

**Issue by Forthoney** [Forthoney/Blehblade#26]
- [x] Implement rudimentary physics
- [x] Make beyblades launch on scene start
- [x] Make appropriate beyblade stop on win or loss
- [x] Smooth out physics

**Comment by Forthoney** [comment]
We should decide how the beyblades initially launch. Should it fly down from the sky? Should it appear out of thin air into the stadium?

**Comment by taj-gillin** [comment]
I think flying down from the sky would be cool and not too difficult.
