### ISSUE TITLE
Make inventory game object

### ISSUE THREAD

**Issue by Forthoney** [Forthoney/Blehblade#36]
Make an inventory game object that manages the display of the inventory object sprites and selection.
It needs a method that takes in InventoryObject and displays it in an inventory slot. It should also handle the selection and return of inventory objects

**Comment by Forthoney** [comment]
@Brian-han77 worked on this this week because @Bokai-Bi wasn't here. I think Brian has it mostly finished, but do let each other know about progress

**Comment by Forthoney** [comment]
@Bokai-Bi How much progress do you have on this?

**Comment by Bokai-Bi** [comment]
Inventory Management system is now working
