### ISSUE TITLE
Fix Inventory Object Release

### ISSUE THREAD

**Issue by jabramson24** [Forthoney/Blehblade#44]
To reproduce issue, go to ProtoPuzzle scene on branch 42-create-sample-level - hit play, grab one of the background objects, and throw it - when trying to grab another object, it just resummons the first one to the foreground. Fix it so that which object is grabbed depends on where the mouse is.

**Comment by Forthoney** [comment]
I worked on the issue and think it's working now. We can see next week and test more rigorously.

On a side note, though, I think your scene is a bit broken. We should make one central, functioning scene from which other people can clone and branch off of.
