### ISSUE TITLE
Make SceneManager

### ISSUE THREAD

**Issue by Forthoney** [Forthoney/Blehblade#6]
### Create SceneManager object and script
The SceneManager system must
- [ ] Identify level results (did the player win or lose?)
- [ ] Trigger win/loss screen accordingly
- [ ] Transition to next scene (level transition)

**Comment by Forthoney** [comment]
If @jabramson24 doesn't come today, will probably have someone else take over

**Comment by jabramson24** [comment]
> If @jabramson24 doesn't come today, will probably have someone else take over

Hey, I'll be here until about 1:45 today. Happy to keep working on it or pass off the issue to someone else.
